from __future__ import annotations

from typing import Any


class MockTopologySource:
    """Mock source that emulates multi-agent architecture signals.

    The source is split by origin so discovery can demonstrate provenance
    and confidence scoring.
    """

    def config_components(self) -> list[dict[str, Any]]:
        return [
            {
                "id": "node.chat_gateway",
                "name": "Chat Gateway",
                "role": "runtime_node",
                "summary": "Entry point for user instructions and streaming responses.",
                "source_type": "agent_config",
                "source_location": "configs/runtime/chat_gateway.yaml",
                "tags": ["entry", "api"],
                "metadata": {"weight": 1.1, "status": "healthy"},
            },
            {
                "id": "node.planner_core",
                "name": "Planner Core",
                "role": "planner",
                "summary": "Creates plans and dispatches sub-agent execution.",
                "source_type": "workflow_graph",
                "source_location": "graphs/orchestrator/plan.graph.json",
                "tags": ["orchestrator", "center"],
                "metadata": {"weight": 1.5, "status": "healthy"},
            },
            {
                "id": "node.retriever_hybrid",
                "name": "Hybrid Retriever",
                "role": "retriever",
                "summary": "Hybrid lexical plus vector retrieval.",
                "source_type": "retrieval_config",
                "source_location": "configs/retrieval/retriever.toml",
                "tags": ["rag"],
                "metadata": {"weight": 1.25, "status": "healthy"},
            },
            {
                "id": "node.reranker_cross",
                "name": "Cross Encoder Reranker",
                "role": "reranker",
                "summary": "Reorders candidates with semantic relevance model.",
                "source_type": "retrieval_config",
                "source_location": "configs/retrieval/reranker.toml",
                "tags": ["rag", "ranking"],
                "metadata": {"weight": 1.0, "status": "healthy"},
            },
            {
                "id": "node.memory_short",
                "name": "Session Memory",
                "role": "memory",
                "summary": "Short-term conversational memory store.",
                "source_type": "memory_config",
                "source_location": "configs/memory/session.yaml",
                "tags": ["memory", "session"],
                "metadata": {"weight": 1.0, "status": "healthy"},
            },
            {
                "id": "node.memory_long",
                "name": "Long-term Memory",
                "role": "memory",
                "summary": "Persistent memory and episodic recall index.",
                "source_type": "memory_config",
                "source_location": "configs/memory/persistent.yaml",
                "tags": ["memory", "persistent"],
                "metadata": {"weight": 1.2, "status": "idle"},
            },
            {
                "id": "node.tool_registry",
                "name": "Tool Registry",
                "role": "tool",
                "summary": "Resolves tool signatures and execution contracts.",
                "source_type": "tool_registry",
                "source_location": "registry/tools.json",
                "tags": ["tooling"],
                "metadata": {"weight": 1.1, "status": "healthy"},
            },
            {
                "id": "node.shell_tool",
                "name": "Shell Tool",
                "role": "tool",
                "summary": "Executes shell commands in sandboxed runtime.",
                "source_type": "tool_registry",
                "source_location": "registry/tools/shell.ts",
                "tags": ["tool", "shell"],
                "metadata": {"weight": 1.0, "status": "warning"},
            },
            {
                "id": "node.browser_tool",
                "name": "Browser Tool",
                "role": "tool",
                "summary": "Controls web automation and page extraction.",
                "source_type": "tool_registry",
                "source_location": "registry/tools/browser.ts",
                "tags": ["tool", "browser"],
                "metadata": {"weight": 1.1, "status": "healthy"},
            },
            {
                "id": "node.mcp_gateway",
                "name": "MCP Gateway",
                "role": "mcp",
                "summary": "Connects tool requests to MCP servers.",
                "source_type": "mcp_registry",
                "source_location": "registry/mcp.json",
                "tags": ["mcp", "integration"],
                "metadata": {"weight": 1.1, "status": "healthy"},
            },
            {
                "id": "node.mcp_result_adapter",
                "name": "MCP Result Adapter",
                "role": "runtime_node",
                "summary": "Transforms MCP result payloads to model-friendly context.",
                "source_type": "mcp_registry",
                "source_location": "runtime/mcp/result_adapter.py",
                "tags": ["mcp", "adapter"],
                "metadata": {"weight": 0.9, "status": "healthy"},
            },
            {
                "id": "node.llm_router",
                "name": "Model Gateway",
                "role": "llm",
                "summary": "Routes prompts to selected LLM providers.",
                "source_type": "llm_gateway_config",
                "source_location": "configs/llm/providers.yaml",
                "tags": ["llm", "gateway"],
                "metadata": {"weight": 1.4, "status": "healthy"},
            },
            {
                "id": "node.prompt_registry",
                "name": "Prompt Registry",
                "role": "prompt",
                "summary": "Stores system prompt templates and policies.",
                "source_type": "prompt_registry",
                "source_location": "registry/prompts.yaml",
                "tags": ["prompt"],
                "metadata": {"weight": 0.8, "status": "idle"},
            },
            {
                "id": "node.guardrail_policy",
                "name": "Guardrail Policy",
                "role": "guardrail",
                "summary": "Checks outputs against policy and risk rules.",
                "source_type": "policy_registry",
                "source_location": "policy/guardrails.yaml",
                "tags": ["safety"],
                "metadata": {"weight": 1.0, "status": "healthy"},
            },
            {
                "id": "node.evaluator",
                "name": "Evaluator",
                "role": "evaluator",
                "summary": "Scores answer quality and confidence.",
                "source_type": "policy_registry",
                "source_location": "policy/evaluator.yaml",
                "tags": ["safety", "quality"],
                "metadata": {"weight": 0.9, "status": "idle"},
            },
            {
                "id": "node.fallback_router",
                "name": "Fallback Router",
                "role": "runtime_node",
                "summary": "Fallback path for retries and degraded responses.",
                "source_type": "workflow_graph",
                "source_location": "graphs/orchestrator/fallback.graph.json",
                "tags": ["fallback"],
                "metadata": {"weight": 0.9, "status": "healthy"},
            },
            {
                "id": "node.final_renderer",
                "name": "Final Renderer",
                "role": "runtime_node",
                "summary": "Composes final answer and stream chunks to client.",
                "source_type": "agent_config",
                "source_location": "runtime/renderer/final_renderer.ts",
                "tags": ["output"],
                "metadata": {"weight": 0.9, "status": "healthy"},
            },
            {
                "id": "node.vector_store",
                "name": "Vector Store",
                "role": "external",
                "summary": "External vector database service.",
                "source_type": "retrieval_config",
                "source_location": "configs/retrieval/vector_store.yaml",
                "tags": ["external", "db"],
                "metadata": {"weight": 1.0, "status": "healthy"},
            },
            {
                "id": "node.external_api",
                "name": "External API",
                "role": "external",
                "summary": "Third-party API boundary for tool calls.",
                "source_type": "tool_registry",
                "source_location": "registry/tools/http_tool.ts",
                "tags": ["external", "api"],
                "metadata": {"weight": 0.9, "status": "warning"},
            },
        ]

    def workflow_relations(self) -> list[dict[str, Any]]:
        return [
            {
                "id": "edge.chat_to_planner",
                "source": "node.chat_gateway",
                "target": "node.planner_core",
                "relation_type": "invocation",
                "protocol": "internal/http+json",
                "confidence": 0.99,
                "inferred_from": ["graphs/orchestrator/plan.graph.json"],
            },
            {
                "id": "edge.planner_to_retriever",
                "source": "node.planner_core",
                "target": "node.retriever_hybrid",
                "relation_type": "dependency",
                "protocol": "internal/http+json",
                "confidence": 0.95,
                "inferred_from": ["graphs/orchestrator/plan.graph.json"],
            },
            {
                "id": "edge.retriever_to_reranker",
                "source": "node.retriever_hybrid",
                "target": "node.reranker_cross",
                "relation_type": "dataflow",
                "protocol": "internal/http+json",
                "confidence": 0.93,
                "inferred_from": ["graphs/rag/retrieve.graph.json"],
            },
            {
                "id": "edge.retriever_to_vector",
                "source": "node.retriever_hybrid",
                "target": "node.vector_store",
                "relation_type": "invocation",
                "protocol": "http+json",
                "confidence": 0.9,
                "inferred_from": ["configs/retrieval/vector_store.yaml"],
            },
            {
                "id": "edge.reranker_to_llm",
                "source": "node.reranker_cross",
                "target": "node.llm_router",
                "relation_type": "dataflow",
                "protocol": "internal/http+json",
                "confidence": 0.89,
                "inferred_from": ["graphs/rag/retrieve.graph.json"],
            },
            {
                "id": "edge.planner_to_memory",
                "source": "node.planner_core",
                "target": "node.memory_short",
                "relation_type": "dataflow",
                "protocol": "internal/http+json",
                "confidence": 0.92,
                "inferred_from": ["configs/memory/session.yaml"],
            },
            {
                "id": "edge.memory_to_llm",
                "source": "node.memory_short",
                "target": "node.llm_router",
                "relation_type": "dataflow",
                "protocol": "internal/http+json",
                "confidence": 0.86,
                "inferred_from": ["runtime/memory/pipeline.py"],
            },
            {
                "id": "edge.planner_to_tool_registry",
                "source": "node.planner_core",
                "target": "node.tool_registry",
                "relation_type": "invocation",
                "protocol": "tool-call",
                "confidence": 0.97,
                "inferred_from": ["registry/tools.json"],
            },
            {
                "id": "edge.tool_registry_to_shell",
                "source": "node.tool_registry",
                "target": "node.shell_tool",
                "relation_type": "invocation",
                "protocol": "shell",
                "confidence": 0.95,
                "inferred_from": ["registry/tools/shell.ts"],
            },
            {
                "id": "edge.tool_registry_to_browser",
                "source": "node.tool_registry",
                "target": "node.browser_tool",
                "relation_type": "invocation",
                "protocol": "ws",
                "confidence": 0.95,
                "inferred_from": ["registry/tools/browser.ts"],
            },
            {
                "id": "edge.tool_registry_to_external",
                "source": "node.tool_registry",
                "target": "node.external_api",
                "relation_type": "invocation",
                "protocol": "http+json",
                "confidence": 0.85,
                "inferred_from": ["registry/tools/http_tool.ts"],
            },
            {
                "id": "edge.planner_to_mcp",
                "source": "node.planner_core",
                "target": "node.mcp_gateway",
                "relation_type": "invocation",
                "protocol": "mcp",
                "confidence": 0.94,
                "inferred_from": ["registry/mcp.json"],
            },
            {
                "id": "edge.mcp_to_tool_registry",
                "source": "node.mcp_gateway",
                "target": "node.tool_registry",
                "relation_type": "invocation",
                "protocol": "mcp",
                "confidence": 0.93,
                "inferred_from": ["registry/mcp.json"],
            },
            {
                "id": "edge.mcp_to_adapter",
                "source": "node.mcp_gateway",
                "target": "node.mcp_result_adapter",
                "relation_type": "dataflow",
                "protocol": "mcp",
                "confidence": 0.9,
                "inferred_from": ["runtime/mcp/result_adapter.py"],
            },
            {
                "id": "edge.adapter_to_llm",
                "source": "node.mcp_result_adapter",
                "target": "node.llm_router",
                "relation_type": "dataflow",
                "protocol": "internal/http+json",
                "confidence": 0.88,
                "inferred_from": ["runtime/mcp/result_adapter.py"],
            },
            {
                "id": "edge.planner_to_llm",
                "source": "node.planner_core",
                "target": "node.llm_router",
                "relation_type": "invocation",
                "protocol": "internal/http+json",
                "confidence": 0.96,
                "inferred_from": ["graphs/orchestrator/plan.graph.json"],
            },
            {
                "id": "edge.llm_to_guardrail",
                "source": "node.llm_router",
                "target": "node.guardrail_policy",
                "relation_type": "dataflow",
                "protocol": "internal/http+json",
                "confidence": 0.92,
                "inferred_from": ["policy/guardrails.yaml"],
            },
            {
                "id": "edge.guardrail_to_renderer",
                "source": "node.guardrail_policy",
                "target": "node.final_renderer",
                "relation_type": "invocation",
                "protocol": "internal/http+json",
                "confidence": 0.91,
                "inferred_from": ["runtime/renderer/final_renderer.ts"],
            },
            {
                "id": "edge.llm_to_renderer",
                "source": "node.llm_router",
                "target": "node.final_renderer",
                "relation_type": "invocation",
                "protocol": "internal/http+json",
                "confidence": 0.95,
                "inferred_from": ["runtime/renderer/final_renderer.ts"],
            },
            {
                "id": "edge.planner_to_fallback",
                "source": "node.planner_core",
                "target": "node.fallback_router",
                "relation_type": "fallback",
                "protocol": "internal/http+json",
                "confidence": 0.9,
                "inferred_from": ["graphs/orchestrator/fallback.graph.json"],
            },
            {
                "id": "edge.fallback_to_renderer",
                "source": "node.fallback_router",
                "target": "node.final_renderer",
                "relation_type": "invocation",
                "protocol": "internal/http+json",
                "confidence": 0.9,
                "inferred_from": ["runtime/renderer/final_renderer.ts"],
            },
        ]

    def python_registration_snippets(self) -> list[dict[str, Any]]:
        return [
            {
                "symbol": "register_agent('claude.orchestrator')",
                "component_id": "node.planner_core",
                "source_location": "parsers/claude_runtime.py",
            },
            {
                "symbol": "@tool(name='shell')",
                "component_id": "node.shell_tool",
                "source_location": "tools/shell_adapter.py",
            },
            {
                "symbol": "MCPClient.register('search')",
                "component_id": "node.mcp_gateway",
                "source_location": "integrations/mcp/client.py",
            },
            {
                "symbol": "ModelGateway.route()",
                "component_id": "node.llm_router",
                "source_location": "llm/gateway.py",
            },
        ]
